#!/usr/bin/env python3
"""
Build airport_profiles.json — enriched operational data for all 522 airports.
Large hubs get fully researched profiles.
Medium/small/regional get intelligent defaults derived from type + state + climate.
"""
import csv, json
from pathlib import Path

ROOT = Path(__file__).parent.parent
AIRPORTS_CSV = ROOT / "data" / "us_airports_full.csv"
OUT_FILE     = ROOT / "data" / "airport_profiles.json"

# ── Climate zones by state ────────────────────────────────────────────────────
STATE_CLIMATE = {
    "AK": ("northern_winter", 74.0, 100),
    "AL": ("southern_humid",   0.2,  117),
    "AR": ("southern_humid",   4.0,  106),
    "AZ": ("desert_dry",       0.1,   37),
    "CA": ("coastal_rain",     0.0,   35),
    "CO": ("mountain",        57.0,   82),
    "CT": ("northern_winter",  45.0,  126),
    "FL": ("tropical",          0.0,  115),
    "GA": ("southern_humid",    2.0,  115),
    "GU": ("tropical",          0.0,  180),
    "HI": ("tropical",          0.0,  278),
    "IA": ("northern_winter",  34.0,  109),
    "ID": ("mountain",         21.0,   90),
    "IL": ("northern_winter",  38.0,  122),
    "IN": ("northern_winter",  28.0,  127),
    "KS": ("northern_winter",  18.0,   95),
    "KY": ("southern_humid",   15.0,  128),
    "LA": ("southern_humid",    0.1,  114),
    "MA": ("northern_winter",  48.0,  126),
    "MD": ("northern_winter",  21.0,  116),
    "ME": ("northern_winter",  71.0,  155),
    "MI": ("northern_winter",  55.0,  133),
    "MN": ("northern_winter",  54.0,  114),
    "MO": ("northern_winter",  18.0,  111),
    "MS": ("southern_humid",    1.0,  115),
    "MT": ("northern_winter",  40.0,   98),
    "NC": ("southern_humid",    5.0,  116),
    "ND": ("northern_winter",  38.0,   97),
    "NE": ("northern_winter",  27.0,   97),
    "NH": ("northern_winter",  60.0,  125),
    "NJ": ("northern_winter",  29.0,  121),
    "NM": ("desert_dry",        7.0,   59),
    "NV": ("desert_dry",        0.5,   26),
    "NY": ("northern_winter",  34.0,  121),
    "OH": ("northern_winter",  28.0,  137),
    "OK": ("southern_humid",    9.0,   90),
    "OR": ("coastal_rain",      6.0,  144),
    "PA": ("northern_winter",  34.0,  124),
    "PR": ("tropical",           0.0,  210),
    "RI": ("northern_winter",  31.0,  125),
    "SC": ("southern_humid",    1.0,  108),
    "SD": ("northern_winter",  40.0,   96),
    "TN": ("southern_humid",    5.0,  119),
    "TX": ("southern_humid",    0.5,   90),
    "UT": ("mountain",         58.0,   92),
    "VA": ("northern_winter",  18.0,  117),
    "VI": ("tropical",           0.0,  252),
    "VT": ("northern_winter",  80.0,  154),
    "WA": ("coastal_rain",      7.0,  164),
    "WI": ("northern_winter",  46.0,  125),
    "WV": ("northern_winter",  29.0,  152),
    "WY": ("mountain",         76.0,   95),
}

# ── Elevation by airport (ft) — notable ones ─────────────────────────────────
ELEVATION = {
    "DEN": 5433, "SLC": 4227, "ABQ": 5355, "ELP": 3958, "TUS": 2643,
    "BZN": 4473, "BOI": 2871, "RNO": 4415, "COS": 6187, "DRO": 6685,
    "GJT": 4858, "ASE": 7820, "JAC": 6451, "CPR": 5350, "BIL": 3652,
    "GEG": 2376, "FCA": 2969, "LWS": 1438, "HLN": 3877, "MSO": 3206,
    "ATL": 1026, "LAX": 126,  "ORD": 672,  "DFW": 607,  "MIA": 8,
    "SFO": 13,   "SEA": 433,  "JFK": 13,   "EWR": 18,   "LGA": 22,
    "BOS": 20,   "MCO": 96,   "LAS": 2181, "PHX": 1135, "CLT": 748,
    "IAH": 98,   "MSP": 841,  "DTW": 639,  "PHL": 36,   "BWI": 146,
    "HNL": 13,   "ANC": 152,
}

# ── Courthouse mapping by state ───────────────────────────────────────────────
COURTHOUSE = {
    "AL": "U.S. District Court for the Northern/Southern District of Alabama",
    "AK": "U.S. District Court for the District of Alaska",
    "AZ": "U.S. District Court for the District of Arizona",
    "AR": "U.S. District Court for the Eastern/Western District of Arkansas",
    "CA": "U.S. District Court for the Central/Northern/Southern District of California",
    "CO": "U.S. District Court for the District of Colorado",
    "CT": "U.S. District Court for the District of Connecticut",
    "FL": "U.S. District Court for the Southern/Middle/Northern District of Florida",
    "GA": "U.S. District Court for the Northern District of Georgia",
    "GU": "U.S. District Court for the District of Guam",
    "HI": "U.S. District Court for the District of Hawaii",
    "ID": "U.S. District Court for the District of Idaho",
    "IL": "U.S. District Court for the Northern District of Illinois",
    "IN": "U.S. District Court for the Southern/Northern District of Indiana",
    "IA": "U.S. District Court for the Northern/Southern District of Iowa",
    "KS": "U.S. District Court for the District of Kansas",
    "KY": "U.S. District Court for the Eastern/Western District of Kentucky",
    "LA": "U.S. District Court for the Eastern District of Louisiana",
    "ME": "U.S. District Court for the District of Maine",
    "MD": "U.S. District Court for the District of Maryland",
    "MA": "U.S. District Court for the District of Massachusetts",
    "MI": "U.S. District Court for the Eastern/Western District of Michigan",
    "MN": "U.S. District Court for the District of Minnesota",
    "MS": "U.S. District Court for the Northern/Southern District of Mississippi",
    "MO": "U.S. District Court for the Eastern/Western District of Missouri",
    "MT": "U.S. District Court for the District of Montana",
    "NE": "U.S. District Court for the District of Nebraska",
    "NV": "U.S. District Court for the District of Nevada",
    "NH": "U.S. District Court for the District of New Hampshire",
    "NJ": "U.S. District Court for the District of New Jersey",
    "NM": "U.S. District Court for the District of New Mexico",
    "NY": "U.S. District Court for the Southern/Eastern/Northern District of New York",
    "NC": "U.S. District Court for the Western/Middle/Eastern District of North Carolina",
    "ND": "U.S. District Court for the District of North Dakota",
    "OH": "U.S. District Court for the Northern/Southern District of Ohio",
    "OK": "U.S. District Court for the Western/Northern/Eastern District of Oklahoma",
    "OR": "U.S. District Court for the District of Oregon",
    "PA": "U.S. District Court for the Eastern/Western/Middle District of Pennsylvania",
    "PR": "U.S. District Court for the District of Puerto Rico",
    "RI": "U.S. District Court for the District of Rhode Island",
    "SC": "U.S. District Court for the District of South Carolina",
    "SD": "U.S. District Court for the District of South Dakota",
    "TN": "U.S. District Court for the Eastern/Middle/Western District of Tennessee",
    "TX": "U.S. District Court for the Northern/Southern/Eastern/Western District of Texas",
    "UT": "U.S. District Court for the District of Utah",
    "VT": "U.S. District Court for the District of Vermont",
    "VA": "U.S. District Court for the Eastern/Western District of Virginia",
    "VI": "U.S. District Court for the District of the Virgin Islands",
    "WA": "U.S. District Court for the Western/Eastern District of Washington",
    "WV": "U.S. District Court for the Northern/Southern District of West Virginia",
    "WI": "U.S. District Court for the Eastern/Western District of Wisconsin",
    "WY": "U.S. District Court for the District of Wyoming",
}

# ── Fully researched large hub profiles ──────────────────────────────────────
LARGE_HUB_PROFILES = {
    "ATL": {
        "annual_passengers_M": 104.0,
        "passenger_tier": "mega",
        "daily_flights_approx": 2700,
        "terminal_count": 7,
        "gate_count_approx": 192,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "SSP America",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 22,
        "major_airlines": ["Delta Air Lines", "Southwest Airlines", "American Airlines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["Delta Air Lines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "City of Atlanta — Hartsfield-Jackson Atlanta International Airport",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Plane Train inter-terminal transit", "International Terminal F baggage claim", "Domestic Terminal baggage carousels 1-12", "Concourse T moving walkways"],
        "airport_specific_hazards": [
            "Plane Train sudden stops and crowded platforms are a leading cause of fall injuries at ATL",
            "ATL's sheer volume — 2,700 daily flights — means cleaning crews cannot keep pace with spills during peak hours",
            "International Terminal F sees the heaviest international baggage volumes in the US, creating carousel overcrowding"
        ],
        "local_context_note": "As the world's busiest airport by passenger count, ATL processes more potential accident victims per hour than any other US airport."
    },
    "ORD": {
        "annual_passengers_M": 77.0,
        "passenger_tier": "mega",
        "daily_flights_approx": 2400,
        "terminal_count": 4,
        "gate_count_approx": 191,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Hudson Group",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "dnata",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 29,
        "major_airlines": ["United Airlines", "American Airlines", "Delta Air Lines", "Southwest Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["United Airlines", "American Airlines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "O'Hare 21 expansion program — new global terminal and satellite concourses, ongoing through 2028",
        "airport_operator_name": "City of Chicago — Chicago Department of Aviation",
        "operator_type": "city",
        "notice_of_claim_days": 365,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Terminal 1 B/C connector tunnel moving walkways", "Terminal 5 international arrivals baggage claim", "O'Hare 21 active construction corridors", "ATS people mover platforms"],
        "airport_specific_hazards": [
            "O'Hare 21 construction creates active hazard zones adjacent to operating terminals — the largest airport construction project in the US",
            "The B/C underground connector tunnel is a notorious congestion point with moving walkways that have a history of mechanical issues",
            "Chicago winters create severe ice accumulation at curbside and outdoor boarding areas — among the worst conditions of any major US airport"
        ],
        "local_context_note": "O'Hare is the nation's second busiest airport and is mid-way through a $12 billion expansion, making it one of the most active construction environments in US aviation."
    },
    "LAX": {
        "annual_passengers_M": 88.0,
        "passenger_tier": "mega",
        "daily_flights_approx": 2000,
        "terminal_count": 9,
        "gate_count_approx": 146,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "LAZ Parking",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 72,
        "major_airlines": ["American Airlines", "Delta Air Lines", "United Airlines", "Southwest Airlines", "Alaska Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": [],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "LAX Automated People Mover (APM) and Consolidated Rent-A-Car facility — major active construction through 2024-2025",
        "airport_operator_name": "Los Angeles World Airports (LAWA) — City of Los Angeles",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["Tom Bradley International Terminal (TBIT) baggage claim", "Curbside upper/lower roadway system", "Inter-terminal shuttle bus route", "Terminal 4-7 connector corridor"],
        "airport_specific_hazards": [
            "LAX's unique split-level roadway creates dangerous pedestrian-vehicle mixing at curbside — a leading source of vehicle collision injuries",
            "The Tom Bradley International Terminal handles some of the heaviest international baggage loads in the US, with 20+ international carriers creating carousel overcrowding",
            "LAX's APM construction zones run adjacent to active terminals — one of the largest active construction hazard areas at any US airport"
        ],
        "local_context_note": "LAX is operated by LAWA, a city department — all claims against the airport itself require a Notice of Claim within 6 months under California Government Code."
    },
    "DFW": {
        "annual_passengers_M": 73.0,
        "passenger_tier": "mega",
        "daily_flights_approx": 2000,
        "terminal_count": 5,
        "gate_count_approx": 165,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 27,
        "major_airlines": ["American Airlines", "United Airlines", "Delta Air Lines", "Southwest Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["American Airlines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Dallas/Fort Worth International Airport Board",
        "operator_type": "joint_authority",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Skylink inter-terminal train platforms", "Terminal D international baggage claim", "Terminal A/B American Airlines gates", "Rental car bus transit center"],
        "airport_specific_hazards": [
            "DFW's Skylink automated train serves all 5 terminals and runs 24 hours — sudden stops on crowded platforms are a consistent injury source",
            "DFW covers 26 square miles making it the second-largest airport complex in the world — inter-terminal distances create rush-induced falls",
            "Texas summer heat creates heat emergency risk in outdoor boarding areas and the extensive curbside system"
        ],
        "local_context_note": "DFW is governed by an independent airport board — a joint authority of Dallas and Fort Worth — with its own legal liability structure separate from either city."
    },
    "DEN": {
        "annual_passengers_M": 77.0,
        "passenger_tier": "mega",
        "daily_flights_approx": 1700,
        "terminal_count": 3,
        "gate_count_approx": 193,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Menzies Aviation",
        "ground_handler_secondary": "Swissport",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 23,
        "major_airlines": ["United Airlines", "Southwest Airlines", "Frontier Airlines", "American Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["United Airlines", "Frontier Airlines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "Concourse expansion and Great Hall modernization project ongoing",
        "airport_operator_name": "Denver International Airport — City and County of Denver",
        "operator_type": "city",
        "notice_of_claim_days": 182,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["Great Hall main terminal concourse", "Automated underground train platforms A/B/C", "Hotel connector walkway", "East/West curbside"],
        "airport_specific_hazards": [
            "Denver's 5,433 ft elevation is the highest of any major US hub — aggravating heart conditions and increasing medical emergency risk in the terminal",
            "DEN's automated train runs underground between concourses — sudden stops on steep entrance escalators have caused significant fall injuries",
            "Denver receives 57 inches of snow annually — the outdoor curbside and parking areas are among the iciest of any major US airport"
        ],
        "local_context_note": "Denver International Airport is city-owned and operated — all claims require a Notice of Claim filed with the City and County of Denver within 182 days."
    },
    "JFK": {
        "annual_passengers_M": 62.0,
        "passenger_tier": "mega",
        "daily_flights_approx": 1400,
        "terminal_count": 6,
        "gate_count_approx": 128,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "OTG Management",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "dnata",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 60,
        "major_airlines": ["American Airlines", "Delta Air Lines", "JetBlue Airways", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["JetBlue Airways"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "New Terminal 6 construction and Terminal 1 rebuild — multi-billion JFK redevelopment program through 2030",
        "airport_operator_name": "Port Authority of New York and New Jersey",
        "operator_type": "port_authority",
        "notice_of_claim_days": 90,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["AirTrain inter-terminal and Jamaica Station", "Terminal 4 international arrivals hall", "Terminal 1/5 active construction corridors", "JetBlue T5 departure concourse"],
        "airport_specific_hazards": [
            "JFK's Port Authority ownership means Notice of Claim must be filed within 90 days — one of the shortest deadlines of any major US airport",
            "The AirTrain connecting terminals and Jamaica/Howard Beach stations has multiple platform gaps and mechanical stop incidents",
            "JFK's multi-billion redevelopment program creates active construction hazards in T1 and T6 areas adjacent to operating gates"
        ],
        "local_context_note": "JFK is operated by the Port Authority of NY and NJ — a bi-state government entity with its own Notice of Claim requirements and liability framework separate from both New York City and New York State."
    },
    "SFO": {
        "annual_passengers_M": 51.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1200,
        "terminal_count": 4,
        "gate_count_approx": 115,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "SSP America",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 44,
        "major_airlines": ["United Airlines", "Alaska Airlines", "American Airlines", "Delta Air Lines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["United Airlines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "San Francisco Airport Commission — City and County of San Francisco",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["International Terminal G boarding areas", "AirTrain platforms", "Terminal 3 E gates United concourse", "Rental car center shuttle"],
        "airport_specific_hazards": [
            "SFO's fog and coastal weather creates year-round wet floor conditions at all terminal entrances — one of the most consistently wet environments of any major US airport",
            "The International Terminal is the largest such terminal in North America — its sheer scale creates disorientation and rushing falls in connection corridors",
            "SFO is built on bay fill and experienced significant seismic damage in the 1989 earthquake — structural assessments are ongoing for older terminal sections"
        ],
        "local_context_note": "SFO is operated by the San Francisco Airport Commission, a city agency — all claims require Notice of Claim under California Government Code within 6 months."
    },
    "SEA": {
        "annual_passengers_M": 52.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1100,
        "terminal_count": 1,
        "gate_count_approx": 90,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "SSP America",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 31,
        "major_airlines": ["Alaska Airlines", "Delta Air Lines", "Southwest Airlines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["Alaska Airlines", "Delta Air Lines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "International Arrivals Facility expansion and North Satellite renovation ongoing",
        "airport_operator_name": "Port of Seattle",
        "operator_type": "port_authority",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Central Terminal main concourse", "North Satellite connector tunnel", "International arrivals facility", "Link Light Rail station connection"],
        "airport_specific_hazards": [
            "Seattle receives 164 rainy days annually — the terminal entrances and curbside at SEA are persistently wet, making them among the most slip-prone in the country",
            "The underground North Satellite connector tunnel has a history of flooding during heavy rain events, creating severe wet floor hazards",
            "SEA's single-building design means all passenger traffic funnels through one central security checkpoint — among the most congested checkpoints in the US during peak hours"
        ],
        "local_context_note": "SEA is operated by the Port of Seattle, a state-chartered public entity — no Notice of Claim filing is required before suit, but the Port's legal team is among the most active of any US airport authority."
    },
    "LAS": {
        "annual_passengers_M": 57.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1400,
        "terminal_count": 3,
        "gate_count_approx": 112,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Hudson Group",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Securitas",
        "airline_count_approx": 29,
        "major_airlines": ["Southwest Airlines", "Spirit Airlines", "Allegiant Air", "American Airlines", "Delta Air Lines"],
        "has_low_cost_carriers": True,
        "is_hub_for": [],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Clark County Department of Aviation",
        "operator_type": "county",
        "notice_of_claim_days": 180,
        "known_litigation_history": True,
        "pfas_risk": "low",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "high",
        "tourist_airport": True,
        "business_airport": False,
        "notable_accident_zones": ["Terminal 1 D gates (high volume Southwest gates)", "Terminal 3 international arrivals", "Slot machine areas in D concourse", "Tram between D and E concourses"],
        "airport_specific_hazards": [
            "LAS is unique among major US airports in having slot machines in the terminal — the distraction factor contributes measurably to walking injuries and falls",
            "Las Vegas handles massive convention traffic surges — during CES, NAB, and other major events, passenger volumes spike far beyond normal, overwhelming cleaning staff",
            "The desert heat creates dehydration and heat-related medical emergencies among tourists unfamiliar with the climate, particularly in outdoor curbside areas"
        ],
        "local_context_note": "Harry Reid International Airport is operated by Clark County — Notice of Claim must be filed within 6 months for government liability claims."
    },
    "MCO": {
        "annual_passengers_M": 57.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1300,
        "terminal_count": 4,
        "gate_count_approx": 131,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "Delaware North",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Prospect Airport Services",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 30,
        "major_airlines": ["Southwest Airlines", "Spirit Airlines", "American Airlines", "Delta Air Lines", "Frontier Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": [],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": False,
        "construction_active": True,
        "construction_notes": "Terminal C North expansion — new gates and facilities through 2025",
        "airport_operator_name": "Greater Orlando Aviation Authority (GOAA)",
        "operator_type": "joint_authority",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "high",
        "tourist_airport": True,
        "business_airport": False,
        "notable_accident_zones": ["Airside 1 and 2 inter-terminal tram", "International terminal baggage claim", "Terminal C construction corridor", "Rental car shuttle stop"],
        "airport_specific_hazards": [
            "MCO serves Walt Disney World, Universal, and Sea World — the highest concentration of elderly and mobility-challenged tourists of any US airport, increasing fall and wheelchair injury risk",
            "Florida's afternoon thunderstorm pattern creates sudden dangerous wet conditions at outdoor curbside and boarding areas daily during summer months",
            "MCO's inter-terminal tram runs between the main terminal and airsides 1-4 — platform gaps and sudden stops are a consistent injury source"
        ],
        "local_context_note": "MCO is operated by the Greater Orlando Aviation Authority — an independent special district with its own liability framework separate from the City of Orlando."
    },
    "MIA": {
        "annual_passengers_M": 52.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1200,
        "terminal_count": 1,
        "gate_count_approx": 131,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "Areas USA",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "dnata",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 55,
        "major_airlines": ["American Airlines", "LATAM Airlines", "Avianca", "Copa Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["American Airlines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Miami-Dade Aviation Department",
        "operator_type": "county",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "high",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["Concourse D Latin American gates", "MIA Mover station", "International arrivals Level 2", "North and South baggage claim areas"],
        "airport_specific_hazards": [
            "MIA serves more Latin American and Caribbean international routes than any other US airport — Montreal Convention international claims are particularly common here",
            "South Florida's year-round humidity and frequent rain creates persistent wet entrance and curbside conditions",
            "MIA's single horseshoe-shaped terminal creates extreme congestion at the central security checkpoint area — among the most crowded in the US"
        ],
        "local_context_note": "MIA is operated by Miami-Dade County — Florida's sovereign immunity rules apply, but international claims under the Montreal Convention are extremely common given MIA's status as the US gateway to Latin America."
    },
    "IAH": {
        "annual_passengers_M": 45.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1100,
        "terminal_count": 5,
        "gate_count_approx": 130,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Menzies Aviation",
        "ground_handler_secondary": "Swissport",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 22,
        "major_airlines": ["United Airlines", "American Airlines", "Southwest Airlines", "Delta Air Lines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["United Airlines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Houston Airport System — City of Houston",
        "operator_type": "city",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Skyway inter-terminal train", "Terminal E international baggage claim", "Terminal B/C United hub gates", "Ground transportation center"],
        "airport_specific_hazards": [
            "Houston's Gulf Coast climate brings intense summer thunderstorms and frequent heavy rain — outdoor curbside areas flood regularly, creating dangerous wet entry conditions",
            "IAH's Skyway inter-terminal train covers 5 terminals across a wide campus — the outdoor sections are exposed to Texas heat and sudden rain",
            "The Energy Corridor business traffic creates extreme early morning peak congestion at the security checkpoints in Terminals B and C"
        ],
        "local_context_note": "IAH is operated by the Houston Airport System, a city department — Texas has no mandatory Notice of Claim requirement for airport injury cases at most facilities."
    },
    "PHX": {
        "annual_passengers_M": 48.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1200,
        "terminal_count": 4,
        "gate_count_approx": 120,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 24,
        "major_airlines": ["American Airlines", "Southwest Airlines", "Delta Air Lines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["American Airlines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "City of Phoenix Aviation Department",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "high",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["Terminal 4 Sky Harbor main concourse", "PHX Sky Train stations", "Rental car center connector", "Terminal 3 outdoor walkways"],
        "airport_specific_hazards": [
            "Phoenix regularly exceeds 115°F in summer — outdoor boarding areas, curbside, and tarmac create serious heat emergency risk, particularly for elderly retirees traveling to/from Phoenix",
            "PHX Sky Train connects terminals and the rental car center via elevated rail — platform transitions and sudden stops are an injury risk",
            "Arizona's monsoon season brings sudden intense downpours July-September — terminal entrances flood rapidly and become extremely slippery"
        ],
        "local_context_note": "Phoenix Sky Harbor is operated by the City of Phoenix Aviation Department — Notice of Claim must be filed within 180 days under Arizona law."
    },
    "CLT": {
        "annual_passengers_M": 53.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1500,
        "terminal_count": 1,
        "gate_count_approx": 95,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "G2 Secure Staff",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 17,
        "major_airlines": ["American Airlines", "Delta Air Lines", "United Airlines", "Southwest Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["American Airlines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Charlotte Douglas International Airport — City of Charlotte",
        "operator_type": "city",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Concourse E American hub gates", "International arrivals baggage claim", "Rocking chairs concourse seating areas", "Ground transportation tunnel"],
        "airport_specific_hazards": [
            "CLT is American Airlines' second-largest hub — extreme gate congestion during AM/PM bank operations creates rush-induced falls at jet bridges and gates",
            "Charlotte's concourses A-E are connected by an underground walkway with moving walkways — transition points are a consistent fall hazard",
            "CLT's rocking chair amenity areas are beloved but create an unusual trip hazard unique to this airport"
        ],
        "local_context_note": "Charlotte Douglas is operated by the City of Charlotte — North Carolina has no mandatory Notice of Claim requirement for personal injury cases against city airports."
    },
    "EWR": {
        "annual_passengers_M": 40.0,
        "passenger_tier": "major",
        "daily_flights_approx": 950,
        "terminal_count": 3,
        "gate_count_approx": 99,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Hudson Group",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 30,
        "major_airlines": ["United Airlines", "American Airlines", "Delta Air Lines", "Spirit Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["United Airlines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "Terminal A replacement — new Terminal One under construction through 2028",
        "airport_operator_name": "Port Authority of New York and New Jersey",
        "operator_type": "port_authority",
        "notice_of_claim_days": 90,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Terminal A construction corridors (active demolition)", "AirTrain monorail stations", "Terminal C United hub gates", "NJ Transit rail connection platform"],
        "airport_specific_hazards": [
            "EWR's Terminal A is actively being demolished and replaced — construction hazard zones are adjacent to operating passenger areas",
            "New Jersey winters are severe — the multi-level roadway system and uncovered parking areas are among the most ice-prone of any major airport",
            "Port Authority ownership means the 90-day Notice of Claim deadline is one of the strictest in the US — missing it permanently bars the claim"
        ],
        "local_context_note": "Newark Liberty is operated by the Port Authority of NY and NJ — the same 90-day Notice of Claim requirement that applies to JFK and LGA applies here."
    },
    "MSP": {
        "annual_passengers_M": 39.0,
        "passenger_tier": "major",
        "daily_flights_approx": 1000,
        "terminal_count": 2,
        "gate_count_approx": 131,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 21,
        "major_airlines": ["Delta Air Lines", "Sun Country Airlines", "United Airlines", "American Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["Delta Air Lines", "Sun Country Airlines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Metropolitan Airports Commission (MAC)",
        "operator_type": "joint_authority",
        "notice_of_claim_days": 180,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Tram between Terminals 1 and 2", "Terminal 1 Lindbergh concourse G/H/J", "Outdoor covered walkways in winter", "Terminal 2 Humphrey small carrier gates"],
        "airport_specific_hazards": [
            "Minneapolis receives 54 inches of snow annually — MSP's outdoor curbside and covered connector walkways are among the most consistently icy of any major US airport",
            "The TRAM connecting Terminals 1 and 2 runs outdoors — in winter conditions, platform gaps and sudden stops create significant injury risk",
            "The Metropolitan Airports Commission requires a 180-day Notice of Claim — a deadline that is frequently missed by out-of-state injury victims"
        ],
        "local_context_note": "MSP is operated by the Metropolitan Airports Commission, a regional government authority — claims require Notice of Claim within 180 days."
    },
    "BOS": {
        "annual_passengers_M": 40.0,
        "passenger_tier": "major",
        "daily_flights_approx": 900,
        "terminal_count": 4,
        "gate_count_approx": 102,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "SSP America",
        "retail_operator": "Hudson Group",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 28,
        "major_airlines": ["JetBlue Airways", "American Airlines", "Delta Air Lines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["JetBlue Airways"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "Terminal E international expansion and Terminal B renovation ongoing",
        "airport_operator_name": "Massachusetts Port Authority (Massport)",
        "operator_type": "state",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["Terminal E international arrivals hall", "Water Transportation Dock ferry connection", "Terminal B JetBlue gates", "Silver Line bus tunnel connection"],
        "airport_specific_hazards": [
            "Boston receives 48 inches of snow annually — Logan's unique peninsula location means strong Atlantic winds accelerate ice formation on all outdoor surfaces",
            "Logan's Terminal E international expansion creates active construction corridors adjacent to the busiest international arrivals hall in New England",
            "The Silver Line bus tunnel and ferry dock create unusual pedestrian-vehicle mixing points not found at most US airports"
        ],
        "local_context_note": "Logan is operated by Massport, a Massachusetts state authority — no Notice of Claim is required before filing suit, but Massport has aggressive in-house legal counsel."
    },
    "DTW": {
        "annual_passengers_M": 35.0,
        "passenger_tier": "major",
        "daily_flights_approx": 900,
        "terminal_count": 2,
        "gate_count_approx": 129,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "G2 Secure Staff",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 20,
        "major_airlines": ["Delta Air Lines", "Spirit Airlines", "American Airlines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["Delta Air Lines"],
        "has_people_mover": True,
        "has_rental_car_facility": True,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Wayne County Airport Authority",
        "operator_type": "county",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["McNamara Terminal A/B/C Delta hub concourses", "Underground tram between McNamara and North Terminal", "North Terminal Spirit/Southwest gates", "Tunnel art installation walkway"],
        "airport_specific_hazards": [
            "DTW's underground tram between McNamara and North Terminal runs through a tunnel with a distinctive light installation — the visual distraction contributes to pedestrian inattention and falls",
            "Michigan winters with 55 inches of snow mean DTW's extensive curbside areas are heavily iced from November through March",
            "Delta's massive hub operation at McNamara creates extreme bank congestion — 300+ aircraft moving through in 90-minute windows with dangerous rushing at gates"
        ],
        "local_context_note": "DTW is operated by the Wayne County Airport Authority — Michigan requires no Notice of Claim before filing personal injury suits against county airport authorities."
    },
    "PHL": {
        "annual_passengers_M": 30.0,
        "passenger_tier": "major",
        "daily_flights_approx": 750,
        "terminal_count": 4,
        "gate_count_approx": 126,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMS Host",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 25,
        "major_airlines": ["American Airlines", "Spirit Airlines", "Delta Air Lines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["American Airlines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "Terminal F demolition and Terminals A-E renovation ongoing",
        "airport_operator_name": "Philadelphia International Airport — City of Philadelphia",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Terminal A/B American hub gates", "Terminal F demolition zone (active)", "Baggage claim carousels 1-12", "SEPTA rail connection platform"],
        "airport_specific_hazards": [
            "PHL consistently ranks among the lowest-rated major US airports for facility quality — aging infrastructure creates more maintenance gaps than comparable hubs",
            "Terminal F demolition creates active hazard zones that border the operational terminal areas",
            "Philadelphia's winters bring significant ice to the outdoor boarding areas and the SEPTA connection walkway"
        ],
        "local_context_note": "PHL is owned and operated by the City of Philadelphia — Notice of Claim must be filed within 6 months under Pennsylvania's Political Subdivision Tort Claims Act."
    },
    "LGA": {
        "annual_passengers_M": 30.0,
        "passenger_tier": "major",
        "daily_flights_approx": 800,
        "terminal_count": 4,
        "gate_count_approx": 72,
        "has_jet_bridges": True,
        "has_international_terminal": False,
        "food_operator": "OTG Management",
        "retail_operator": "Hudson Group",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Prospect Airport Services",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 20,
        "major_airlines": ["Delta Air Lines", "American Airlines", "United Airlines", "Southwest Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": [],
        "has_people_mover": True,
        "has_rental_car_facility": False,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "LGA transformation complete 2023 — new Central Hall and Terminals B/C opened",
        "airport_operator_name": "Port Authority of New York and New Jersey",
        "operator_type": "port_authority",
        "notice_of_claim_days": 90,
        "known_litigation_history": True,
        "pfas_risk": "low",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Central Hall main concourse (newly opened)", "AirTrain people mover between terminals", "Curbside upper/lower roadway", "Terminal B Delta concourse"],
        "airport_specific_hazards": [
            "LGA's new construction has fresh surfaces but new transition points between old and new sections create unexpected level changes",
            "LGA's constrained Queens location means the curbside is one of the most congested vehicle-pedestrian mixing zones of any US airport",
            "Port Authority's 90-day Notice of Claim deadline — identical to JFK and EWR — is the most critical legal deadline at this airport"
        ],
        "local_context_note": "LaGuardia is operated by the Port Authority of NY and NJ — the same strict 90-day Notice of Claim requirement applies as at JFK and EWR."
    },
    "BWI": {
        "annual_passengers_M": 27.0,
        "passenger_tier": "major",
        "daily_flights_approx": 700,
        "terminal_count": 1,
        "gate_count_approx": 84,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 18,
        "major_airlines": ["Southwest Airlines", "American Airlines", "Delta Air Lines", "Spirit Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["Southwest Airlines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Maryland Aviation Administration (MAA)",
        "operator_type": "state",
        "notice_of_claim_days": 365,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Concourse D Southwest hub gates", "International Pier D/E connector", "MARC train station connector walkway", "Hourly parking garage walkways"],
        "airport_specific_hazards": [
            "BWI is Southwest Airlines' largest hub — the extreme volume of Southwest passengers creates the most crowded concourse D in US aviation per gate",
            "Maryland requires a 1-year Notice of Claim — the longest of any state aviation authority but one that is still frequently missed",
            "Baltimore winters bring significant ice to the outdoor connector walkways between the terminal and parking structures"
        ],
        "local_context_note": "BWI is operated by the Maryland Aviation Administration, a state agency — Notice of Claim must be filed within 1 year under Maryland's Tort Claims Act."
    },
    "DCA": {
        "annual_passengers_M": 24.0,
        "passenger_tier": "major",
        "daily_flights_approx": 650,
        "terminal_count": 3,
        "gate_count_approx": 44,
        "has_jet_bridges": True,
        "has_international_terminal": False,
        "food_operator": "HMSHost",
        "retail_operator": "Hudson Group",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Prospect Airport Services",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 15,
        "major_airlines": ["American Airlines", "Southwest Airlines", "Delta Air Lines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["American Airlines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "New Terminal and Concourse expansion — major construction through 2027",
        "airport_operator_name": "Metropolitan Washington Airports Authority (MWAA)",
        "operator_type": "joint_authority",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "low",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["New terminal construction corridors", "Gate 35X outdoor boarding area", "Metro station pedestrian connection", "Shuttle buses between terminals"],
        "airport_specific_hazards": [
            "DCA's Gate 35X is one of the most notorious outdoor boarding gates at any major US airport — passengers board via buses to remote aircraft, creating outdoor stair and tarmac injuries",
            "The new terminal construction at DCA creates active hazard zones immediately adjacent to the oldest operating terminal section",
            "DCA's Metro connection and constrained footprint create one of the highest pedestrian-vehicle conflict rates at any major US airport curbside"
        ],
        "local_context_note": "Reagan National is operated by MWAA, a bi-state authority — no Notice of Claim is required, but MWAA operates under a hybrid federal-state legal framework due to its proximity to federal property."
    },
    "HNL": {
        "annual_passengers_M": 21.0,
        "passenger_tier": "major",
        "daily_flights_approx": 550,
        "terminal_count": 3,
        "gate_count_approx": 56,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 20,
        "major_airlines": ["Hawaiian Airlines", "Southwest Airlines", "American Airlines", "Delta Air Lines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["Hawaiian Airlines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Hawaii Department of Transportation — Airports Division",
        "operator_type": "state",
        "notice_of_claim_days": 0,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "high",
        "tourist_airport": True,
        "business_airport": False,
        "notable_accident_zones": ["Inter-island terminal open-air walkways", "International arrivals baggage claim", "Outdoor inter-terminal walkway connections", "Commuter terminal small aircraft areas"],
        "airport_specific_hazards": [
            "HNL is one of the few major US airports with largely open-air terminals — the tropical rain and humidity create persistent wet walking surfaces throughout the facility",
            "Hawaii's 278 rainy days annually mean that outdoor inter-terminal walkways are wet for most of the year — the highest rain exposure of any US airport",
            "HNL handles more elderly international tourists per gate than almost any US airport — Japan and Australia visitor demographics significantly increase fall and medical emergency risk"
        ],
        "local_context_note": "HNL is operated by the Hawaii Department of Transportation Airports Division, a state agency — Hawaii does not require Notice of Claim before personal injury suits against state airport authorities."
    },
    "ANC": {
        "annual_passengers_M": 5.0,
        "passenger_tier": "major",
        "daily_flights_approx": 200,
        "terminal_count": 2,
        "gate_count_approx": 26,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "Delaware North",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "Airport-operated",
        "ground_handler_primary": "Menzies Aviation",
        "ground_handler_secondary": "Unknown",
        "cart_operator": "Smarte Carte",
        "security_contractor": "TSA-only",
        "airline_count_approx": 12,
        "major_airlines": ["Alaska Airlines", "United Airlines", "Delta Air Lines"],
        "has_low_cost_carriers": False,
        "is_hub_for": [],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Ted Stevens Anchorage International Airport — Municipality of Anchorage",
        "operator_type": "city",
        "notice_of_claim_days": 120,
        "known_litigation_history": False,
        "pfas_risk": "high",
        "worker_injury_risk": "high",
        "elderly_passenger_risk": "low",
        "tourist_airport": True,
        "business_airport": False,
        "notable_accident_zones": ["Cargo ramp area (world's 4th busiest cargo airport)", "Outdoor boarding areas in extreme cold", "C concourse international gates", "Curbside in ice and snow"],
        "airport_specific_hazards": [
            "Anchorage receives 74 inches of snow annually with temperatures regularly below -10°F — outdoor surfaces at ANC are among the most extreme weather hazard conditions of any commercial US airport",
            "ANC is the world's 4th busiest cargo airport — the cargo ramp area has extremely heavy ground vehicle traffic creating significant worker injury risk",
            "PFAS contamination from decades of military fire training at the adjacent Elmendorf Air Force Base has been documented in ANC groundwater — a significant environmental liability"
        ],
        "local_context_note": "ANC is operated by the Municipality of Anchorage — Alaska requires Notice of Claim within 120 days for claims against municipal entities."
    },
    "SAN": {
        "annual_passengers_M": 26.0,
        "passenger_tier": "major",
        "daily_flights_approx": 600,
        "terminal_count": 2,
        "gate_count_approx": 52,
        "has_jet_bridges": True,
        "has_international_terminal": False,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 18,
        "major_airlines": ["Southwest Airlines", "American Airlines", "Alaska Airlines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": [],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "New Terminal 1 construction — major redevelopment through 2027",
        "airport_operator_name": "San Diego County Regional Airport Authority",
        "operator_type": "joint_authority",
        "notice_of_claim_days": 180,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "high",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["New Terminal 1 construction zones adjacent to T2", "Terminal 2 Commuter gates outdoor boarding", "Airport water taxi/trolley connection", "Rental car shuttle center"],
        "airport_specific_hazards": [
            "SAN's new Terminal 1 construction runs adjacent to active operations — one of the largest construction hazard zones at a California airport",
            "SAN's unique urban location means aircraft fly at extremely low altitudes over surrounding neighborhoods — noise complaints and stress injuries from aircraft operations are documented",
            "The commuter terminal at SAN uses outdoor boarding stairs for most regional flights — weather exposure including marine layer fog creates slippery conditions"
        ],
        "local_context_note": "SAN is operated by the San Diego County Regional Airport Authority — Notice of Claim must be filed within 6 months under California Government Code."
    },
    "SJC": {
        "annual_passengers_M": 12.0,
        "passenger_tier": "major",
        "daily_flights_approx": 300,
        "terminal_count": 2,
        "gate_count_approx": 30,
        "has_jet_bridges": True,
        "has_international_terminal": False,
        "food_operator": "SSP America",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Unknown",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 12,
        "major_airlines": ["Southwest Airlines", "Alaska Airlines", "American Airlines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": [],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "City of San José — Norman Y. Mineta San José International Airport",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": False,
        "pfas_risk": "low",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Terminal A/B connector walkway", "Rental car shuttle bus route", "VTA light rail station connector"],
        "airport_specific_hazards": [
            "SJC's Silicon Valley location means a high concentration of business travelers carrying expensive electronics equipment — theft and luggage damage claims are elevated",
            "The light rail connection creates an unusual pedestrian path from city transit into the terminal — a crossing point prone to falls during wet Silicon Valley winters",
            "SJC handles significant international tech worker travel — passport control queues during peak arrivals create extended standing and DVT risk"
        ],
        "local_context_note": "SJC is operated by the City of San José — all claims require Notice of Claim within 6 months under California Government Code section 911.2."
    },
    "PDX": {
        "annual_passengers_M": 20.0,
        "passenger_tier": "major",
        "daily_flights_approx": 500,
        "terminal_count": 1,
        "gate_count_approx": 70,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "SSP America",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Menzies Aviation",
        "ground_handler_secondary": "Swissport",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 15,
        "major_airlines": ["Alaska Airlines", "Southwest Airlines", "Delta Air Lines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": [],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "Port of Portland",
        "operator_type": "port_authority",
        "notice_of_claim_days": 180,
        "known_litigation_history": False,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "medium",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["Main terminal A/B/C connector corridor", "MAX light rail station at terminal", "Outdoor curbside during heavy rain", "International arrivals baggage claim"],
        "airport_specific_hazards": [
            "Portland receives 144 rainy days annually — PDX's renowned indoor nature areas and local food marketplace mean high foot traffic on perpetually wet tile floors",
            "The MAX light rail stops directly at the terminal — the outdoor platform and connection walkway are exposed to Portland's consistent autumn-winter rainfall",
            "PDX is regularly cited as one of America's best airports — its high retail and dining density means more crowded queuing areas and elevated spill risk"
        ],
        "local_context_note": "PDX is operated by the Port of Portland — Oregon's Notice of Claim requirement of 180 days applies to all claims against Port facilities."
    },
    "SLC": {
        "annual_passengers_M": 27.0,
        "passenger_tier": "major",
        "daily_flights_approx": 700,
        "terminal_count": 2,
        "gate_count_approx": 80,
        "has_jet_bridges": True,
        "has_international_terminal": True,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Menzies Aviation",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 16,
        "major_airlines": ["Delta Air Lines", "Southwest Airlines", "American Airlines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["Delta Air Lines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": True,
        "construction_notes": "New SLC Airport — Terminal 2 Phase 2 construction ongoing through 2025",
        "airport_operator_name": "Salt Lake City Department of Airports",
        "operator_type": "city",
        "notice_of_claim_days": 365,
        "known_litigation_history": False,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "high",
        "tourist_airport": True,
        "business_airport": True,
        "notable_accident_zones": ["Terminal 2 active construction zones", "TRAX light rail station connection", "New terminal concourse A/B", "Ski equipment baggage claim area"],
        "airport_specific_hazards": [
            "SLC's 4,227 ft elevation affects passengers with cardiac and respiratory conditions — the high altitude and Utah's low humidity create acute medical emergency risk, particularly for older travelers",
            "SLC handles massive ski tourism traffic November-April — ski equipment bags and oversized winter gear create significant baggage claim hazards",
            "Phase 2 construction is active alongside newly opened Terminal 1 — construction corridors create hazards for first-time visitors navigating a still-changing layout"
        ],
        "local_context_note": "SLC is operated by the Salt Lake City Department of Airports — Utah requires a 1-year Notice of Claim for personal injury cases against city departments."
    },
    "MDW": {
        "annual_passengers_M": 21.0,
        "passenger_tier": "major",
        "daily_flights_approx": 600,
        "terminal_count": 1,
        "gate_count_approx": 43,
        "has_jet_bridges": True,
        "has_international_terminal": False,
        "food_operator": "HMSHost",
        "retail_operator": "Hudson Group",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": "Unknown",
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 8,
        "major_airlines": ["Southwest Airlines", "Delta Air Lines", "American Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": ["Southwest Airlines"],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": True,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": "City of Chicago — Chicago Department of Aviation",
        "operator_type": "city",
        "notice_of_claim_days": 365,
        "known_litigation_history": True,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Southwest Airlines terminal — all gates", "Orange Line CTA station connector", "Curbside dropoff in winter conditions", "Single baggage claim carousel area"],
        "airport_specific_hazards": [
            "MDW is essentially a Southwest Airlines-only airport — the single airline's boarding style (no assigned seats) creates dangerous rushing and crowding at all gates",
            "MDW's single baggage claim carousel is one of the most congested in US aviation for its passenger volume — falling bag and carousel injuries are disproportionately high",
            "Chicago winter conditions and MDW's exposed curbside location on the city's southwest side create severe ice and snow hazards from November through March"
        ],
        "local_context_note": "Midway is operated by the City of Chicago Department of Aviation — the same 1-year Notice of Claim requirement applies as at O'Hare."
    },
}

# ── Default profile templates by airport type ────────────────────────────────

def default_profile_medium(airport: dict, climate: tuple) -> dict:
    climate_zone, snow, rain = climate
    return {
        "annual_passengers_M": 5.0,
        "passenger_tier": "major",
        "daily_flights_approx": 150,
        "terminal_count": 1,
        "gate_count_approx": 20,
        "has_jet_bridges": True,
        "has_international_terminal": False,
        "food_operator": "HMSHost",
        "retail_operator": "Paradies Lagardere",
        "parking_operator": "SP Plus",
        "ground_handler_primary": "Swissport",
        "ground_handler_secondary": None,
        "cart_operator": "Smarte Carte",
        "security_contractor": "Allied Universal",
        "airline_count_approx": 8,
        "major_airlines": ["American Airlines", "Delta Air Lines", "United Airlines"],
        "has_low_cost_carriers": True,
        "is_hub_for": [],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": f"{airport['city']} Airport Authority",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": False,
        "pfas_risk": "medium",
        "worker_injury_risk": "medium",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": True,
        "notable_accident_zones": ["Main terminal concourse", "Baggage claim area", "Curbside dropoff", "Parking garage walkway"],
        "airport_specific_hazards": _climate_hazards(climate_zone, snow, rain, airport['city']),
        "local_context_note": f"{airport['airport_name']} serves {airport['city']} and the surrounding region — {_climate_note(climate_zone, snow)}",
    }

def default_profile_small(airport: dict, climate: tuple) -> dict:
    climate_zone, snow, rain = climate
    return {
        "annual_passengers_M": 0.8,
        "passenger_tier": "regional",
        "daily_flights_approx": 25,
        "terminal_count": 1,
        "gate_count_approx": 6,
        "has_jet_bridges": True,
        "has_international_terminal": False,
        "food_operator": "Delaware North",
        "retail_operator": "Hudson Group",
        "parking_operator": "Airport-operated",
        "ground_handler_primary": "Prospect Airport Services",
        "ground_handler_secondary": None,
        "cart_operator": "Airport-operated",
        "security_contractor": "TSA-only",
        "airline_count_approx": 4,
        "major_airlines": ["American Airlines", "Delta Air Lines", "United Airlines"],
        "has_low_cost_carriers": False,
        "is_hub_for": [],
        "has_people_mover": False,
        "has_rental_car_facility": True,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": f"{airport['city']} Airport Authority",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": False,
        "pfas_risk": "low",
        "worker_injury_risk": "low",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": False,
        "notable_accident_zones": ["Terminal concourse", "Baggage claim", "Curbside dropoff", "Rental car area"],
        "airport_specific_hazards": _climate_hazards(climate_zone, snow, rain, airport['city']),
        "local_context_note": f"{airport['airport_name']} is a small hub serving {airport['city']} — {_climate_note(climate_zone, snow)}",
    }

def default_profile_nonhub(airport: dict, climate: tuple) -> dict:
    climate_zone, snow, rain = climate
    return {
        "annual_passengers_M": 0.2,
        "passenger_tier": "small",
        "daily_flights_approx": 8,
        "terminal_count": 1,
        "gate_count_approx": 3,
        "has_jet_bridges": False,
        "has_international_terminal": False,
        "food_operator": "Airport-operated",
        "retail_operator": "Airport-operated",
        "parking_operator": "Airport-operated",
        "ground_handler_primary": "Airline-operated",
        "ground_handler_secondary": None,
        "cart_operator": "None",
        "security_contractor": "TSA-only",
        "airline_count_approx": 2,
        "major_airlines": ["American Eagle", "Delta Connection", "United Express"],
        "has_low_cost_carriers": False,
        "is_hub_for": [],
        "has_people_mover": False,
        "has_rental_car_facility": False,
        "has_light_rail_connection": False,
        "construction_active": False,
        "construction_notes": "",
        "airport_operator_name": f"{airport['city']} Municipal Airport",
        "operator_type": "city",
        "notice_of_claim_days": 180,
        "known_litigation_history": False,
        "pfas_risk": "low",
        "worker_injury_risk": "low",
        "elderly_passenger_risk": "medium",
        "tourist_airport": False,
        "business_airport": False,
        "notable_accident_zones": ["Terminal building", "Baggage claim area", "Boarding stairs to aircraft", "Outdoor ramp area"],
        "airport_specific_hazards": _climate_hazards(climate_zone, snow, rain, airport['city'], non_hub=True),
        "local_context_note": f"{airport['airport_name']} is a regional airport serving {airport['city']} — all boarding is via outdoor stairs, creating unique weather-related hazard exposure.",
    }

def _climate_hazards(zone: str, snow: float, rain: int, city: str, non_hub: bool = False) -> list:
    hazards = []
    if zone == "northern_winter" and snow > 40:
        hazards.append(f"{city} receives significant annual snowfall — ice accumulation at outdoor boarding areas and curbside is a seasonal hazard from November through March")
    elif zone == "northern_winter":
        hazards.append(f"{city}'s winter weather creates periodic ice and snow conditions at all outdoor airport surfaces — a recurring slip and fall risk")
    elif zone == "tropical":
        hazards.append(f"{city}'s tropical climate means year-round high humidity and frequent rain — terminal entrances and curbside are persistently wet")
    elif zone == "coastal_rain":
        hazards.append(f"{city}'s coastal climate with {rain}+ rainy days annually creates persistent wet conditions at terminal entrances and outdoor areas")
    elif zone == "desert_dry":
        hazards.append(f"{city}'s desert climate creates extreme heat conditions in summer — outdoor boarding areas and curbside create heat emergency risk")
    elif zone == "mountain":
        hazards.append(f"{city}'s mountain location means significant snow and high altitude — both create unique injury and medical emergency risks")
    elif zone == "southern_humid":
        hazards.append(f"{city}'s humid climate with {rain}+ rainy days creates regular wet floor conditions and seasonal storm-related flooding at curbside areas")

    if non_hub:
        hazards.append(f"All aircraft boarding at this regional airport uses outdoor stairs — passengers are fully exposed to weather conditions during the boarding process")
        hazards.append("Regional airports typically have reduced cleaning and maintenance staff, increasing the time hazardous conditions remain unaddressed")
    else:
        hazards.append("Reduced staffing during early morning and late night operations means hazards take longer to be addressed at off-peak hours")

    return hazards

def _climate_note(zone: str, snow: float) -> str:
    if zone == "northern_winter" and snow > 50:
        return "the harsh northern winter significantly increases outdoor slip and fall risk from November through April"
    elif zone == "northern_winter":
        return "winter weather conditions create seasonal outdoor slip and fall risk"
    elif zone == "tropical":
        return "the tropical climate means year-round rain and humidity affect walking surfaces"
    elif zone == "desert_dry":
        return "extreme summer heat creates medical emergency risk for outdoor activities"
    elif zone == "mountain":
        return "the high elevation and mountain weather create unique injury and medical risks"
    return "local weather conditions affect outdoor walking surfaces seasonally"


# ── Build all profiles ────────────────────────────────────────────────────────

def build_all_profiles():
    with open(AIRPORTS_CSV) as f:
        airports = list(csv.DictReader(f))

    profiles = {}

    for airport in airports:
        iata = airport['iata_code'] or airport['faa_code']
        sc   = airport['state_code']
        climate = STATE_CLIMATE.get(sc, ("northern_winter", 20.0, 120))

        # Base profile
        if iata in LARGE_HUB_PROFILES:
            profile = LARGE_HUB_PROFILES[iata].copy()
        elif airport['type'] == 'large_hub':
            # Large hub not in our manual list — use a rich default
            profile = default_profile_medium(airport, climate)
            profile['annual_passengers_M'] = 8.0
            profile['passenger_tier'] = 'major'
            profile['daily_flights_approx'] = 300
            profile['gate_count_approx'] = 50
            profile['has_jet_bridges'] = True
        elif airport['type'] == 'medium_hub':
            profile = default_profile_medium(airport, climate)
        elif airport['type'] == 'small_hub':
            profile = default_profile_small(airport, climate)
        else:
            profile = default_profile_nonhub(airport, climate)

        # Always add these from lookup tables
        profile['climate_zone']        = climate[0]
        profile['avg_annual_snow_inches'] = climate[1]
        profile['avg_annual_rain_days']   = climate[2]
        profile['elevation_ft']           = ELEVATION.get(iata, 500)
        profile['nearby_courthouse']      = COURTHOUSE.get(sc, "U.S. District Court (district varies)")

        # Elevation risk flag
        if profile['elevation_ft'] > 4000:
            profile['high_altitude_medical_risk'] = True
        else:
            profile['high_altitude_medical_risk'] = False

        # PFAS upgrade for airports with known military history or fire training
        military_airports = {'ANC','FLL','HNL','MCO','TUS','ABQ','BDL','BHM','OKC','MCI','OMA','TLH','MSY'}
        if iata in military_airports:
            profile['pfas_risk'] = 'high'

        profiles[airport['slug']] = {
            "iata_code":    iata,
            "faa_code":     airport['faa_code'],
            "airport_name": airport['airport_name'],
            "city":         airport['city'],
            "state":        airport['state'],
            "state_code":   airport['state_code'],
            "type":         airport['type'],
            "slug":         airport['slug'],
            **profile
        }

    return profiles


if __name__ == "__main__":
    print("Building airport profiles...")
    profiles = build_all_profiles()

    # Save
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_FILE, 'w') as f:
        json.dump(profiles, f, indent=2)

    # Stats
    total = len(profiles)
    fully_researched = len(LARGE_HUB_PROFILES)
    has_jet_bridges_true  = sum(1 for p in profiles.values() if p.get('has_jet_bridges'))
    has_intl              = sum(1 for p in profiles.values() if p.get('has_international_terminal'))
    pfas_high             = sum(1 for p in profiles.values() if p.get('pfas_risk') == 'high')
    high_altitude         = sum(1 for p in profiles.values() if p.get('high_altitude_medical_risk'))

    print(f"\n✓ Built {total} airport profiles")
    print(f"  Fully researched (large hub):  {fully_researched}")
    print(f"  Default medium/small/regional: {total - fully_researched}")
    print(f"  Has jet bridges:               {has_jet_bridges_true}")
    print(f"  Has international terminal:    {has_intl}")
    print(f"  High PFAS risk:                {pfas_high}")
    print(f"  High altitude (>4000ft):       {high_altitude}")
    print(f"\n  Output: {OUT_FILE}")
    print(f"  File size: {OUT_FILE.stat().st_size / 1024:.0f}KB")

    # Sample — show LAX profile
    lax = profiles.get('los-angeles-international', {})
    print(f"\nSample — LAX:")
    for k, v in lax.items():
        if isinstance(v, list):
            print(f"  {k}: {v[:2]}{'...' if len(v)>2 else ''}")
        else:
            print(f"  {k}: {v}")
